"""Add about_me, last_seen

Revision ID: 090ba6ef67ce
Revises: 5628ae8b881b
Create Date: 2024-12-18 22:14:56.616161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090ba6ef67ce'
down_revision = '5628ae8b881b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
