"""Add User model

Revision ID: 50060160b329
Revises: fea9873cd9a0
Create Date: 2024-12-09 19:16:31.712905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50060160b329'
down_revision = 'fea9873cd9a0'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
