"""Post + User

Revision ID: 8e522a77ab34
Revises: 50060160b329
Create Date: 2024-12-09 20:22:50.639050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e522a77ab34'
down_revision = '50060160b329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
