"""add author field to Post model

Revision ID: fea9873cd9a0
Revises: d0fd1e5179b3
Create Date: 2024-12-02 23:53:12.694426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea9873cd9a0'
down_revision = 'd0fd1e5179b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=120), nullable=True))
        batch_op.alter_column('publish_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('publish_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('author')

    # ### end Alembic commands ###
